// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQHZg9LYyZ1KSbyTEpdXU6jZNQhP70DGA',
    appId: '1:216043399216:android:1f56e18939c080d0bc65f5',
    messagingSenderId: '216043399216',
    projectId: 'test-firebase-f23ae',
    storageBucket: 'test-firebase-f23ae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxcr1yxT9sgJntuSZTzKJ5QCj3Gvz3p2Y',
    appId: '1:216043399216:ios:ded8c5cfed250154bc65f5',
    messagingSenderId: '216043399216',
    projectId: 'test-firebase-f23ae',
    storageBucket: 'test-firebase-f23ae.appspot.com',
    iosClientId:
        '216043399216-5f565ihng8chijmrfharoajnklusp377.apps.googleusercontent.com',
    iosBundleId: 'com.example.OSF',
  );
}
